// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eDk1sxfFp6m8calbzSCy3HTc_AruYeY',
    appId: '1:766006855906:web:a58aad382100f0b572b6bb',
    messagingSenderId: '766006855906',
    projectId: 'aqua-care-app-e33a9',
    authDomain: 'aqua-care-app-e33a9.firebaseapp.com',
    storageBucket: 'aqua-care-app-e33a9.firebasestorage.app',
    measurementId: 'G-PRGCLN2SNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUu78MV9PRWCULglJyPejlPasCFilLTog',
    appId: '1:766006855906:android:c17947c847dad59172b6bb',
    messagingSenderId: '766006855906',
    projectId: 'aqua-care-app-e33a9',
    storageBucket: 'aqua-care-app-e33a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgHdj8a-5SlW9jX6F4hqTVSEG8B7ALHhg',
    appId: '1:766006855906:ios:78d4c5e23429d5a872b6bb',
    messagingSenderId: '766006855906',
    projectId: 'aqua-care-app-e33a9',
    storageBucket: 'aqua-care-app-e33a9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgHdj8a-5SlW9jX6F4hqTVSEG8B7ALHhg',
    appId: '1:766006855906:ios:78d4c5e23429d5a872b6bb',
    messagingSenderId: '766006855906',
    projectId: 'aqua-care-app-e33a9',
    storageBucket: 'aqua-care-app-e33a9.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7eDk1sxfFp6m8calbzSCy3HTc_AruYeY',
    appId: '1:766006855906:web:5cf4b0d2c87ae1a072b6bb',
    messagingSenderId: '766006855906',
    projectId: 'aqua-care-app-e33a9',
    authDomain: 'aqua-care-app-e33a9.firebaseapp.com',
    storageBucket: 'aqua-care-app-e33a9.firebasestorage.app',
    measurementId: 'G-QF4DQE1K3J',
  );
}
